algo:
  _target_: holomotion.src.algo.ppo.PPO
  _recursive_: false
  config:
    # --- General Settings ---
    use_accelerate: ${use_accelerate}
    num_learning_iterations: 300000
    log_interval: 5
    save_interval: 500
    eval_interval: null
    load_optimizer: false
    headless: ${headless}
    compile_model: true
    # ---

    # --- PPO Related Settings ---
    normalize_rewards: false
    num_steps_per_env: 24
    num_learning_epochs: 3
    num_mini_batches: 3
    clip_param: 0.2
    gamma: 0.99
    lam: 0.95
    value_loss_coef: 1.0
    entropy_coef: 0.0
    actor_learning_rate: 1.0e-05
    critic_learning_rate: 1.0e-05
    max_grad_norm: 1.0
    use_clipped_value_loss: false
    schedule: constant
    desired_kl: 0.02
    init_noise_std: 0.3
    # ---

    # --- Dagger Related Settings ---
    teacher_actor_ckpt_path: ???
    dagger_only: true
    dagger_init_coef: 1.0
    dagger_anneal: false
    dagger_anneal_degree: 1.0e-05
    rl_init_coef: 0.0
    rl_warmup: false
    rl_warmup_degree: 1.0e-05
    load_critic_when_dagger: false
    use_teacher_rollout_annealing: true
    teacher_rollout_init_prob: 1.0
    teacher_rollout_min_prob: 0.0
    teacher_rollout_anneal_degree: 5.0e-5
    # ---

    # --- AMP Related Settings ---
    load_disc: false
    disc_loss_coef: 2.0
    disc_grad_penalty_coef: 0.1
    task_rew_coef: 1.0
    amp_rew_coef: 1.0
    amp_rew_scale: 1.0
    adaptive_disc_rew: false
    disc_loss_type: lsgan
    # ---

    # --- Auxiliary Task Related Settings ---
    num_rigid_bodies: ${robot.num_bodies}
    num_extended_bodies: ${robot.num_extend_bodies}
    predict_local_body_pos: false
    pred_local_body_pos_alpha: 1.0
    predict_local_body_vel: false
    pred_local_body_vel_alpha: 0.01
    predict_root_lin_vel: false
    pred_root_lin_vel_alpha: 0.04
    # ---

    # --- Module Settings ---
    module_dict:
      teacher_actor:
        type: MoEMLP
        fix_sigma: false
        use_layernorm: false
        input_dim:
          - teacher_obs
        output_dim:
          - robot_action_dim
        max_sigma: 1.2
        min_sigma: 0.2
        clamp_output:
          enabled: true
          raw_lower_bound: ${robot.dof_pos_lower_limit_list}
          raw_upper_bound: ${robot.dof_pos_upper_limit_list}
          action_scale: ${robot.control.action_scale}
          default_dof_pos_dict: ${robot.init_state.default_joint_angles}
          dof_order: ${robot.dof_names}
        num_fine_experts: 5
        num_shared_experts: 1
        top_k: 2
        load_balancing_loss_alpha: 0.01
        bound_loss_alpha: 10.0
        projection_dim: 2048
        hidden_dim: 1024

      actor:
        type: TFStudent
        fix_sigma: true
        input_dim:
          - actor_obs
        output_dim:
          - robot_action_dim
        patch_size: 4
        fut_patch_size: 1
        predict_local_body_pos: false
        predict_local_body_vel: false
        predict_root_lin_vel: false
        layer_config:
          hidden_dim: 256
          num_layers: 6
        clamp_output:
          enabled: true
          raw_lower_bound: ${robot.dof_pos_lower_limit_list}
          raw_upper_bound: ${robot.dof_pos_upper_limit_list}
          action_scale: ${robot.control.action_scale}
          default_dof_pos_dict: ${robot.init_state.default_joint_angles}
          dof_order: ${robot.dof_names}

      critic: {}

      disc: {}
