name: holomotion_train
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - mesalib
  - pytorch-cuda=12.1
  - pytorch==2.4.1 
  - torchvision==0.19.1 
  - torchaudio==2.4.1
  - pip:
    - -r requirements/requirements_train.txt
    - -e ./thirdparties/SMPLSim
    - -e ./thirdparties/isaacgym/python
    - -e .
