# @package _global_

terrain:
  static_friction: 1.0
  dynamic_friction: 1.0
  restitution: 0.0

  mesh_type: "trimesh" # "heightfield" # none, plane, heightfield or trimesh
  horizontal_scale: 0.2 # [m]
  vertical_scale: 0.002 # [m] - reduced from 0.005 to create more subtle unevenness
  border_size: 40 # [m]
  curriculum: False
  # curriculum : False
  # rough terrain only:
  measure_heights: False # keep it False
  measured_points_x: [0.] # 1mx1.6m rectangle (without center line)
  measured_points_y: [0.]
  selected: False # select a unique terrain type and pass all arguments
  terrain_kwargs: null # Dict of arguments for selected terrain
  max_init_terrain_level: 9 # starting curriculum state
  terrain_length: 8.
  terrain_width: 8.
  num_rows: 10 # number of terrain rows (levels)
  num_cols: 20 # number of terrain cols (types)
  terrain_types: ["flat", "rough"] # reduced to just flat and rough for dancing
  terrain_proportions: [0.3, 0.7] # more rough terrain for testing robustness
  # trimesh only:
  slope_treshold: 0.75 # slopes above this threshold will be corrected to vertical surfaces
