device: "cuda"
policy_freq: 50 # Hz
control_freq: 200 # Hz
control_decimation: 4
msg_type: "hg" # "hg" or "go"
imu_type: "pelvis" # "torso" or "pelvis"
lowcmd_topic: "/lowcmd"
lowstate_topic: "/lowstate"
action_topic: "/humanoid/action"


new_policy_path: "stand_squat_model.onnx"  # default model for stand and squat
policy_path: "horizon_holomotion_model_23dof.onnx"  # motion model

# Basic motion files for squat and stand actions
# motion_file_squat2stand: B button (stand up)
# motion_file_stand2squat: X button (squat down)

motion_file_squat2stand: "deploy_23dof_squat_stand/squat2stand.pkl"  
motion_file_stand2squat: "deploy_23dof_squat_stand/stand2squat.pkl" 

# Dance motion configuration
# dance_motions_dir: Directory containing all dance motion files
# up button: previous dance motion (index -1)
# down button: next dance motion (index +1) 
# right button: first dance motion (index 0)
# left button: last dance motion (index -1)

dance_motions_dir: "motions"  # Directory containing dance motion files

context_length: 47
num_fut_frames: 1
num_bodies_extend: 27
num_dofs: 23
num_actions: 23
action_scale: 0.25
obs_scales:
  base_ang_vel: 0.25
  projected_gravity: 1.0
  dof_pos: 1.0
  dof_vel: 0.05
  actions: 1.0
  ref_motion_phase: 1.0
  history_actor: 1.0
  ref_dof_pos_flat: 1.0
  ref_dof_vel_flat: 1.0
  ref_motion_state_flat: 1.0

normalization:
  obs_clip: 100.0
  action_clip: 100.0

serialization_schema:
  - obs_name: student_actor_realworld_obs_seq
    seq_len: 48
    feat_dim: 75
  - obs_name: fut_ref_motion_seq
    seq_len: 1
    feat_dim: 459
  - obs_name: fut_ref_valid_mask
    seq_len: 1
    feat_dim: 1

current_obs:
  - base_ang_vel
  - projected_gravity
  - dof_pos
  - dof_vel
  - actions
  - history_actor
  - ref_motion_state_flat

history_obs:
  actions: -1
  base_ang_vel: -1
  dof_pos: -1
  dof_vel: -1
  projected_gravity: -1

obs_dims:
  base_ang_vel: 3
  projected_gravity: 3
  dof_pos: 23
  dof_vel: 23
  actions: 23
  ref_motion_phase: 1
  ref_motion_state_flat: 426

complete_dof_order:
  - left_hip_pitch_joint
  - left_hip_roll_joint
  - left_hip_yaw_joint
  - left_knee_joint
  - left_ankle_pitch_joint
  - left_ankle_roll_joint
  - right_hip_pitch_joint
  - right_hip_roll_joint
  - right_hip_yaw_joint
  - right_knee_joint
  - right_ankle_pitch_joint
  - right_ankle_roll_joint
  - waist_yaw_joint
  - waist_roll_joint
  - waist_pitch_joint
  - left_shoulder_pitch_joint
  - left_shoulder_roll_joint
  - left_shoulder_yaw_joint
  - left_elbow_joint
  - left_wrist_roll_joint
  - left_wrist_pitch_joint
  - left_wrist_yaw_joint
  - right_shoulder_pitch_joint
  - right_shoulder_roll_joint
  - right_shoulder_yaw_joint
  - right_elbow_joint
  - right_wrist_roll_joint
  - right_wrist_pitch_joint
  - right_wrist_yaw_joint

policy_dof_order:
  - left_hip_pitch_joint
  - left_hip_roll_joint
  - left_hip_yaw_joint
  - left_knee_joint
  - left_ankle_pitch_joint
  - left_ankle_roll_joint

  - right_hip_pitch_joint
  - right_hip_roll_joint
  - right_hip_yaw_joint
  - right_knee_joint
  - right_ankle_pitch_joint
  - right_ankle_roll_joint

  - waist_yaw_joint
  - waist_roll_joint
  - waist_pitch_joint

  - left_shoulder_pitch_joint
  - left_shoulder_roll_joint
  - left_shoulder_yaw_joint
  - left_elbow_joint

  - right_shoulder_pitch_joint
  - right_shoulder_roll_joint
  - right_shoulder_yaw_joint
  - right_elbow_joint

dof2motor_idx_mapping:
  # https://support.unitree.com/home/zh/G1_developer/about_G1
  left_hip_pitch_joint: 0
  left_hip_roll_joint: 1
  left_hip_yaw_joint: 2
  left_knee_joint: 3
  left_ankle_pitch_joint: 4
  left_ankle_roll_joint: 5
  right_hip_pitch_joint: 6
  right_hip_roll_joint: 7
  right_hip_yaw_joint: 8
  right_knee_joint: 9
  right_ankle_pitch_joint: 10
  right_ankle_roll_joint: 11
  waist_yaw_joint: 12
  waist_roll_joint: 13
  waist_pitch_joint: 14
  left_shoulder_pitch_joint: 15
  left_shoulder_roll_joint: 16
  left_shoulder_yaw_joint: 17
  left_elbow_joint: 18
  left_wrist_roll_joint: 19
  left_wrist_pitch_joint: 20
  left_wrist_yaw_joint: 21
  right_shoulder_pitch_joint: 22
  right_shoulder_roll_joint: 23
  right_shoulder_yaw_joint: 24
  right_elbow_joint: 25
  right_wrist_roll_joint: 26
  right_wrist_pitch_joint: 27
  right_wrist_yaw_joint: 28

control_params:
  stiffness:
    left_hip_pitch_joint: 100.0
    left_hip_roll_joint: 100.0
    left_hip_yaw_joint: 100.0
    left_knee_joint: 150.0
    left_ankle_pitch_joint: 40.0
    left_ankle_roll_joint: 40.0

    right_hip_pitch_joint: 100.0
    right_hip_roll_joint: 100.0
    right_hip_yaw_joint: 100.0
    right_knee_joint: 150.0
    right_ankle_pitch_joint: 40.0
    right_ankle_roll_joint: 40.0

    waist_yaw_joint: 400.0
    waist_roll_joint: 400.0
    waist_pitch_joint: 400.0

    left_shoulder_pitch_joint: 100.0
    left_shoulder_roll_joint: 100.0
    left_shoulder_yaw_joint: 50.0
    left_elbow_joint: 50.0

    left_wrist_roll_joint: 10.0
    left_wrist_pitch_joint: 10.0
    left_wrist_yaw_joint: 10.0

    right_shoulder_pitch_joint: 100.0
    right_shoulder_roll_joint: 100.0
    right_shoulder_yaw_joint: 50.0
    right_elbow_joint: 50.0

    right_wrist_roll_joint: 10.0
    right_wrist_pitch_joint: 10.0
    right_wrist_yaw_joint: 10.0

  damping:
    left_hip_pitch_joint: 2.0
    left_hip_roll_joint: 2.0
    left_hip_yaw_joint: 2.0
    left_knee_joint: 4.0
    left_ankle_pitch_joint: 2.0
    left_ankle_roll_joint: 2.0

    right_hip_pitch_joint: 2.0
    right_hip_roll_joint: 2.0
    right_hip_yaw_joint: 2.0
    right_knee_joint: 4.0
    right_ankle_pitch_joint: 2.0
    right_ankle_roll_joint: 2.0

    waist_yaw_joint: 5.0
    waist_roll_joint: 5.0
    waist_pitch_joint: 5.0

    left_shoulder_pitch_joint: 2.0
    left_shoulder_roll_joint: 2.0
    left_shoulder_yaw_joint: 2.0
    left_elbow_joint: 2.0
    left_wrist_roll_joint: 0.1
    left_wrist_pitch_joint: 0.1
    left_wrist_yaw_joint: 0.1

    right_shoulder_pitch_joint: 2.0
    right_shoulder_roll_joint: 2.0
    right_shoulder_yaw_joint: 2.0
    right_elbow_joint: 2.0
    right_wrist_roll_joint: 0.1
    right_wrist_pitch_joint: 0.1
    right_wrist_yaw_joint: 0.1

default_joint_angles:
  left_hip_pitch_joint: -0.1
  left_hip_roll_joint: 0.0
  left_hip_yaw_joint: 0.0
  left_knee_joint: 0.3
  left_ankle_pitch_joint: -0.2
  left_ankle_roll_joint: 0.0

  right_hip_pitch_joint: -0.1
  right_hip_roll_joint: 0.0
  right_hip_yaw_joint: 0.0
  right_knee_joint: 0.3
  right_ankle_pitch_joint: -0.2
  right_ankle_roll_joint: 0.0

  waist_yaw_joint: 0.0
  waist_roll_joint: 0.0
  waist_pitch_joint: 0.0

  left_shoulder_pitch_joint: 0.2
  left_shoulder_roll_joint: 0.2
  left_shoulder_yaw_joint: 0.0
  left_elbow_joint: 0.9
  left_wrist_roll_joint: 0.0
  left_wrist_pitch_joint: 0.0
  left_wrist_yaw_joint: 0.0

  right_shoulder_pitch_joint: 0.2
  right_shoulder_roll_joint: -0.2
  right_shoulder_yaw_joint: 0.0
  right_elbow_joint: 0.9
  right_wrist_roll_joint: 0.0
  right_wrist_pitch_joint: 0.0
  right_wrist_yaw_joint: 0.0

default_joint_angles_squat:
  left_hip_pitch_joint: -2.5
  left_hip_roll_joint: 0.1
  left_hip_yaw_joint: 0.05
  left_knee_joint: 2.91
  left_ankle_pitch_joint: -0.86
  left_ankle_roll_joint: 0.0

  right_hip_pitch_joint: -2.5
  right_hip_roll_joint: -0.06
  right_hip_yaw_joint: -0.03
  right_knee_joint: 2.9
  right_ankle_pitch_joint: -0.87
  right_ankle_roll_joint: 0.0

  waist_yaw_joint: -0.0
  waist_roll_joint: -0.03
  waist_pitch_joint: 0.47

  left_shoulder_pitch_joint: -0.39
  left_shoulder_roll_joint: 0.68
  left_shoulder_yaw_joint: -0.08
  left_elbow_joint: 0.92
  left_wrist_roll_joint: 0.0
  left_wrist_pitch_joint: 0.0
  left_wrist_yaw_joint: 0.0

  right_shoulder_pitch_joint: -0.47
  right_shoulder_roll_joint: -0.7
  right_shoulder_yaw_joint: -0.58
  right_elbow_joint: 0.77
  right_wrist_roll_joint: -0.0
  right_wrist_pitch_joint: -0.0
  right_wrist_yaw_joint: 0.0


joint_limits:
  position:
    left_hip_pitch_joint: [-2.5307, 2.8798]
    left_hip_roll_joint: [-0.5236, 2.9671]
    left_hip_yaw_joint: [-2.7576, 2.7576]
    left_knee_joint: [-0.087267, 2.8798]
    left_ankle_pitch_joint: [-0.87267, 0.5236]
    left_ankle_roll_joint: [-0.2618, 0.2618]
    right_hip_pitch_joint: [-2.5307, 2.8798]
    right_hip_roll_joint: [-2.9671, 0.5236]
    right_hip_yaw_joint: [-2.7576, 2.7576]
    right_knee_joint: [-0.087267, 2.8798]
    right_ankle_pitch_joint: [-0.87267, 0.5236]
    right_ankle_roll_joint: [-0.2618, 0.2618]
    waist_yaw_joint: [-2.618, 2.618]
    waist_roll_joint: [-0.52, 0.52]
    waist_pitch_joint: [-0.52, 0.52]
    left_shoulder_pitch_joint: [-3.0892, 2.6704]
    left_shoulder_roll_joint: [-1.5882, 2.2515]
    left_shoulder_yaw_joint: [-2.618, 2.618]
    left_elbow_joint: [-1.0472, 2.0944]
    right_shoulder_pitch_joint: [-3.0892, 2.6704]
    right_shoulder_roll_joint: [-2.2515, 1.5882]
    right_shoulder_yaw_joint: [-2.618, 2.618]
    right_elbow_joint: [-1.0472, 2.0944]

  velocity:
    left_hip_pitch_joint: 32
    left_hip_roll_joint: 20
    left_hip_yaw_joint: 32
    left_knee_joint: 20
    left_ankle_pitch_joint: 37
    left_ankle_roll_joint: 37
    right_hip_pitch_joint: 32
    right_hip_roll_joint: 20
    right_hip_yaw_joint: 32
    right_knee_joint: 20
    right_ankle_pitch_joint: 37
    right_ankle_roll_joint: 37
    waist_yaw_joint: 32
    waist_roll_joint: 37
    waist_pitch_joint: 37
    left_shoulder_pitch_joint: 37
    left_shoulder_roll_joint: 37
    left_shoulder_yaw_joint: 37
    left_elbow_joint: 37
    right_shoulder_pitch_joint: 37
    right_shoulder_roll_joint: 37
    right_shoulder_yaw_joint: 37
    right_elbow_joint: 37

  effort:
    left_hip_pitch_joint: 88
    left_hip_roll_joint: 139
    left_hip_yaw_joint: 88
    left_knee_joint: 139
    left_ankle_pitch_joint: 50
    left_ankle_roll_joint: 50
    right_hip_pitch_joint: 88
    right_hip_roll_joint: 139
    right_hip_yaw_joint: 88
    right_knee_joint: 139
    right_ankle_pitch_joint: 50
    right_ankle_roll_joint: 50
    waist_yaw_joint: 88
    waist_roll_joint: 50
    waist_pitch_joint: 50
    left_shoulder_pitch_joint: 25
    left_shoulder_roll_joint: 25
    left_shoulder_yaw_joint: 25
    left_elbow_joint: 25
    right_shoulder_pitch_joint: 25
    right_shoulder_roll_joint: 25
    right_shoulder_yaw_joint: 25
    right_elbow_joint: 25
limit_scales:
  position: 2.0 # Allows 50% more range of motion
  velocity: 2.0 
  effort: 2.0 
