# @package _global_

rewards:
  set_reward: Maiyue
  set_reward_date: 20250707
  only_positive_rewards: false

  reward_scales:
    l2_tracking_root_rpy: 3.0
    l2_rel_tracking_root_lin_vel: 4.0
    l2_rel_tracking_root_ang_vel: 2.0
    l2_rel_tracking_keybody_pos: 4.0
    l2_tracking_joint_position: 6.0
    termination: -200.0
    penalty_action_rate: -0.5
    penalty_action_smooth: -0.5
    penalty_power: -0.001
    penalty_torques: -1.0e-06
    penalty_slippage: -1.0
    limits_dof_pos: -10.0
    limits_dof_vel: -1.0
    limits_torque: -1.0
    l2_feet_vel: 2.0
    l2_root_rel_tracking_endpoints: 4.0
    l2_root_rel_tracking_body_pos: 2.0
    l2_root_rel_tracking_body_rot: 2.0
    l2_root_rel_tracking_body_vel: 2.0
    l2_root_rel_tracking_body_ang_vel: 2.0
    l1_root_rel_tracking_torso_rot: 2.0
    l2_tracking_joint_velocity: 3.0

  l2_rel_tracking_keybody_pos_upper_weight: 0.5
  l2_rel_tracking_keybody_pos_lower_weight: 0.5
  l2_tracking_joint_pos_upper_weight: 0.5
  l2_tracking_joint_pos_lower_weight: 0.5
  l2_tracking_joint_vel_upper_weight: 0.5
  l2_tracking_joint_vel_lower_weight: 0.5

  reward_tracking_sigma:
    l2_rel_tracking_root_lin_vel: 0.1
    l2_rel_tracking_root_ang_vel: 2.0
    l2_rel_tracking_keybody_pos_upper: 0.01
    l2_rel_tracking_keybody_pos_lower: 0.01
    l2_tracking_joint_pos_upper: 0.1
    l2_tracking_joint_pos_lower: 0.1
    l2_tracking_root_rpy: 0.1
    l2_feet_vel: 0.1
    l2_tracking_waist_pitch_roll_dof_pos: 0.15
    l2_root_rel_tracking_body_pos: 0.05
    l2_root_rel_tracking_body_rot: 0.1
    l2_root_rel_tracking_body_vel: 0.1
    l2_root_rel_tracking_body_ang_vel: 3.0
    l2_root_rel_tracking_endpoints: 0.05
    l1_root_rel_tracking_torso_rot: 0.2
    l2_tracking_joint_vel_upper: 3.0
    l2_tracking_joint_vel_lower: 3.0

  reward_penalty_curriculum: false
  reward_initial_penalty_scale: 0.1
  reward_min_penalty_scale: 0.001
  reward_max_penalty_scale: 1.0
  reward_penalty_level_down_threshold: 50
  reward_penalty_level_up_threshold: 50
  reward_penalty_degree: 1.0e-06

  reward_limit:
    soft_dof_pos_limit: 1.0
    soft_dof_vel_limit: 1.0
    soft_torque_limit: 1.0

    reward_limits_curriculum:
      soft_dof_pos_curriculum: false
      soft_dof_pos_initial_limit: 1.5
      soft_dof_pos_max_limit: 1.5
      soft_dof_pos_min_limit: 1.0
      soft_dof_pos_curriculum_degree: ${rewards.reward_penalty_degree}
      soft_dof_pos_curriculum_level_down_threshold: ${rewards.reward_penalty_level_down_threshold}
      soft_dof_pos_curriculum_level_up_threshold: ${rewards.reward_penalty_level_up_threshold}

      soft_dof_vel_curriculum: false
      soft_dof_vel_initial_limit: 1.5
      soft_dof_vel_max_limit: 1.5
      soft_dof_vel_min_limit: 1.0
      soft_dof_vel_curriculum_degree: ${rewards.reward_penalty_degree}
      soft_dof_vel_curriculum_level_down_threshold: ${rewards.reward_penalty_level_down_threshold}
      soft_dof_vel_curriculum_level_up_threshold: ${rewards.reward_penalty_level_up_threshold}

      soft_torque_curriculum: true
      soft_torque_initial_limit: 1.2
      soft_torque_max_limit: 1.2
      soft_torque_min_limit: 1.0
      soft_torque_curriculum_degree: ${rewards.reward_penalty_degree}
      soft_torque_curriculum_level_down_threshold: ${rewards.reward_penalty_level_down_threshold}
      soft_torque_curriculum_level_up_threshold: ${rewards.reward_penalty_level_up_threshold}

  reward_penalty_reward_names:
    - penalty_torques
    - penalty_dof_acc
    - penalty_dof_vel
    - penalty_action_rate
    - limits_dof_pos
    - limits_dof_vel
    - limits_torque
    - feet_heading_alignment
    - penalty_feet_ori
    - penalty_slippage
    - penalty_power
    - penalty_action_smooth

  use_waist_dof_curriculum: false
  waist_dof_curriculum_level_down_mpjpe_threshold: 0.25
  waist_dof_curriculum_level_up_mpjpe_threshold: 0.35
  waist_dof_curriculum_degree: 1.0e-06
  reward_waist_dof_penalty_reward_names:
    - penalty_l1_waist_roll_pitch_dof
  l2_root_rel_tracking_keybody_pos_upper_weight: 0.5
  l2_root_rel_tracking_keybody_pos_lower_weight: 0.5
