# @package _global_

domain_rand:
  # push robots
  push_robots: True
  push_interval_s: [5, 10]
  max_push_vel_xy: 0.2

  # base com
  randomize_base_com: True
  base_com_range:
    x: [-0.05, 0.05]
    y: [-0.05, 0.05]
    z: [-0.05, 0.05]

  # link mass
  randomize_link_mass: True
  link_mass_range: [0.8, 1.2]

  # pd gain
  randomize_pd_gain: True
  kp_range: [0.9, 1.1]
  kd_range: [0.9, 1.1]

  # friction
  randomize_friction: True
  friction_range: [0.5, 1.5]

  # base mass
  randomize_base_mass: True
  added_mass_range: [-1.0, 3.0]

  # rfi
  randomize_torque_rfi: True
  rfi_lim: 0.1
  randomize_rfi_lim: True
  rfi_lim_range: [0.9, 1.1]

  # control delay
  randomize_ctrl_delay: True
  ctrl_delay_step_range: [0, 2] # integer max real delay is 90ms

  # joint default position
  randomize_joint_default_pos: false
  joint_default_pos_range: [-0.01, 0.01]  # radians, bias range for default joint positions
