# @package _global_

defaults:
  - _self_
  - /robot: robot_base

hydra:
  job:
    chdir: false

num_jobs: 4
retargeted_pkl_path: ???
lmdb_save_dir: ???

val_ratio: 0.05
random_seed: 42

# LMDB Map Size Configuration
initial_map_size: 100_485_760 # 100 MiB (bytes)
map_growth_factor: 2.0 # Increase size by 50% when full
max_retries: 100 # Max attempts to resize before failing
