# @package _global_

obs:
  actor_context_length: 47
  context_length: 0
  n_fut_frames: 1
  target_fps: 50

  obs_dict:
    actor_obs:
      - priocep_with_fut_ref_v9_student
    teacher_obs:
      - priocep_with_fut_ref_v7_moe
    critic_obs: ${obs.obs_dict.teacher_obs}

  serialization_schema:
    - obs_name: student_actor_realworld_obs_seq
      seq_len: ${eval:'${obs.actor_context_length} + 1'}
      feat_dim: ${eval:'${robot.dof_obs_size}*3 + 6'}
    - obs_name: fut_ref_motion_seq
      seq_len: ${eval:'${obs.n_fut_frames}'}
      feat_dim: ${eval:'2 + 3+ 3 + (${robot.num_bodies} + ${robot.num_extend_bodies})*(3+6) + ${robot.dof_obs_size}*2'}
    - obs_name: fut_ref_valid_mask
      seq_len: ${eval:'${obs.n_fut_frames}'}
      feat_dim: 1

  student_obs_noise_scales:
    dof_pos: 0.01
    dof_vel: 1.0
    projected_gravity: 0.2
    base_ang_vel: 0.3

  obs_auxiliary:
    history_actor:
      base_ang_vel: ${obs.actor_context_length}
      projected_gravity: ${obs.actor_context_length}
      dof_pos: ${obs.actor_context_length}
      dof_vel: ${obs.actor_context_length}
      actions: ${obs.actor_context_length}

  obs_scales:
    base_rpy: 1.0
    base_height: 1.0
    projected_gravity: 1.0
    rel_base_lin_vel: 2.0
    rel_base_ang_vel: 0.25
    base_ang_vel: 0.25
    dof_pos: 1.0
    dof_vel: 0.05
    actions: 1.0
    local_body_pos_flat: 1.0
    local_body_rot_quat_flat: 1.0
    local_body_vel_flat: 1.0
    local_body_ang_vel_flat: 1.0
    limb_weight_params: 1.0
    dif_local_rigid_body_pos_flat: 1.0
    dif_local_rigid_body_rot_flat: 1.0
    dif_local_rigid_body_vel_flat: 1.0
    dif_local_rigid_body_ang_vel_flat: 1.0
    local_ref_rigid_body_pos_flat: 1.0
    local_ref_rigid_body_rot_flat: 1.0
    history_actor: 1.0
    history_critic: 1.0
    amp_agent_seq: 1.0
    local_key_pos: 1.0
    domain_params: 1.0
    root_rel_bodylink_pos_flat: 1.0
    root_rel_bodylink_vel_flat: 1.0
    root_rel_bodylink_ang_vel_flat: 1.0
    root_rel_bodylink_rot_tannorm_flat: 1.0
    rel_fut_ref_motion_state_flat: 1.0
    mogen_dof_pos: 1.0
    priocep_with_fut_ref_v7_moe: 1.0
    priocep_with_fut_ref_v9_student: 1.0

  noise_scales:
    base_rpy: 0.0
    base_height: 0.0
    projected_gravity: 0.0
    rel_base_lin_vel: 0.0
    rel_base_ang_vel: 0.0
    base_ang_vel: 0.0
    dof_pos: 0.0
    dof_vel: 0.0
    actions: 0.0
    local_body_pos_flat: 0.0
    local_body_rot_quat_flat: 0.0
    local_body_vel_flat: 0.0
    local_body_ang_vel_flat: 0.0
    limb_weight_params: 0.0
    dif_local_rigid_body_pos_flat: 0.0
    dif_local_rigid_body_rot_flat: 0.0
    dif_local_rigid_body_vel_flat: 0.0
    dif_local_rigid_body_ang_vel_flat: 0.0
    local_ref_rigid_body_pos_flat: 0.0
    local_ref_rigid_body_rot_flat: 0.0
    history_actor: 0.0
    history_critic: 0.0
    amp_agent_seq: 0.0
    local_key_pos: 0.0
    domain_params: 0.0
    root_rel_bodylink_pos_flat: 0.0
    root_rel_bodylink_vel_flat: 0.0
    root_rel_bodylink_ang_vel_flat: 0.0
    root_rel_bodylink_rot_tannorm_flat: 0.0
    rel_fut_ref_motion_state_flat: 0.0
    mogen_dof_pos: 0.0
    priocep_with_fut_ref_v7_moe: 0.0
    priocep_with_fut_ref_v9_student: 0.0

  add_noise_currculum: False
  noise_initial_value: 0.0
  noise_value_max: 0.0
  noise_value_min: 0.0
  soft_dof_pos_curriculum_degree: 0.0
  soft_dof_pos_curriculum_level_down_threshold: 40
  soft_dof_pos_curriculum_level_up_threshold: 42

  obs_dims:
    - mogen_dof_pos: ${robot.dof_obs_size}
    - base_rpy: 3
    - base_height: 1
    - projected_gravity: 3
    - rel_base_lin_vel: 3
    - rel_base_ang_vel: 3
    - base_ang_vel: 3
    - dof_pos: ${robot.dof_obs_size}
    - dof_vel: ${robot.dof_obs_size}
    - actions: ${robot.dof_obs_size}
    - local_body_pos_flat: ${eval:'3 * ${robot.num_bodies}'}
    - local_body_rot_quat_flat: ${eval:'4 * ${robot.num_bodies}'}
    - local_body_vel_flat: ${eval:'3 * ${robot.num_bodies}'}
    - local_body_ang_vel_flat: ${eval:'3 * ${robot.num_bodies}'}
    - limb_weight_params: ${robot.num_limb_groups}
    - dif_local_rigid_body_pos_flat: ${eval:'3 * ${obs.n_fut_frames} * (${robot.num_bodies} + ${robot.num_extend_bodies})'}
    - dif_local_rigid_body_rot_flat: ${eval:'4 * ${obs.n_fut_frames} * (${robot.num_bodies} + ${robot.num_extend_bodies})'}
    - dif_local_rigid_body_vel_flat: ${eval:'3 * ${obs.n_fut_frames} * (${robot.num_bodies} + ${robot.num_extend_bodies})'}
    - dif_local_rigid_body_ang_vel_flat: ${eval:'3 * ${obs.n_fut_frames} * (${robot.num_bodies} + ${robot.num_extend_bodies})'}
    - local_ref_rigid_body_pos_flat: ${eval:'3 * ${obs.n_fut_frames} * (${robot.num_bodies} + ${robot.num_extend_bodies})'}
    - local_ref_rigid_body_rot_flat: ${eval:'4 * ${obs.n_fut_frames} * (${robot.num_bodies} + ${robot.num_extend_bodies})'}
    - amp_agent_seq: ${eval:'${env.config.amp_context_length} * (3 + 3 + 3 + ${robot.dof_obs_size} * 2 + (3 * ${robot.num_key_bodies}))'}
    - local_key_pos: ${eval:'3 * ${robot.num_key_bodies}'}
    - domain_params: ${eval:'3 + len(${robot.randomize_link_body_names}) + 2 * ${robot.dof_obs_size} + 1 + 1 + 1 + ${robot.dof_obs_size}'}
    - root_rel_bodylink_pos_flat: ${eval:'3 * (${robot.num_bodies} + ${robot.num_extend_bodies})'}
    - root_rel_bodylink_vel_flat: ${eval:'3 * (${robot.num_bodies} + ${robot.num_extend_bodies})'}
    - root_rel_bodylink_ang_vel_flat: ${eval:'3 * (${robot.num_bodies} + ${robot.num_extend_bodies})'}
    - root_rel_bodylink_rot_tannorm_flat: ${eval:'6 * (${robot.num_bodies} + ${robot.num_extend_bodies})'}
    - rel_fut_ref_motion_state_flat: ${eval:'${obs.n_fut_frames} * (9 + (${robot.num_bodies} + ${robot.num_extend_bodies})*(3+6+3+3) + ${robot.dof_obs_size}*2)'}
    - priocep_with_fut_ref_v7_moe: ${eval:'3 + 3 + 3 + ${robot.dof_obs_size}*3 + (${robot.num_bodies} + ${robot.num_extend_bodies})*(3+6+3+3) + 3 + len(${robot.randomize_link_body_names}) + 2 * ${robot.dof_obs_size} + 1 + 1 + 1 + ${robot.dof_obs_size} + ${obs.n_fut_frames} * (2 + 3 + 3 + (${robot.num_bodies} + ${robot.num_extend_bodies})*(3+6+3+3) + ${robot.dof_obs_size}*2)'}
    - priocep_with_fut_ref_v9_student: ${eval:'${obs.serialization_schema[0].feat_dim} * ${obs.serialization_schema[0].seq_len} + ${obs.serialization_schema[1].feat_dim} * ${obs.serialization_schema[1].seq_len} + ${obs.serialization_schema[2].feat_dim} * ${obs.serialization_schema[2].seq_len}'}
  post_compute_config: {} # Will store values after preprocessing, don't put anything here
