# @package _global_

robot:
  humanoid_type: hi2_21dof
  base_link_name: "base_link"
  num_bodies: 22
  dof_obs_size: 21
  actions_dim: 21
  lower_body_actions_dim: 13
  upper_body_actions_dim: 8
  policy_obs_dim: -1
  critic_obs_dim: -1
  num_key_bodies: 4
  num_limb_groups: 5
  num_extend_bodies: 3
  contact_bodies: ["left_ankle_roll_link", "right_ankle_roll_link"]
  num_feet: 2
  right_foot_name: "right_ankle_roll_link"
  left_foot_name: "left_ankle_roll_link"
  foot_name: "ankle_roll_link"
  knee_name: "knee_link"
  has_torso: True
  torso_name: "base_link"
  has_upper_body_dof: True
  has_key_bodies: True

  # Observation parameters
  # number_of_actions: ???
  # self_obs_max_coords: ???
  algo_obs_dim_dict: ???

  contact_pairs_multiplier: 16

  mimic_small_marker_bodies: null

  hand_link:
    - "left_hand_link"
    - "right_hand_link"

  key_bodies:
    [
      "left_ankle_roll_link",
      "left_knee_link",
      "right_ankle_roll_link",
      "right_knee_link",
      "left_shoulder_yaw_link",
      "left_elbow_link",
      "right_elbow_link",
      "right_shoulder_yaw_link",
    ]

  dof_names:
    [
      "left_shoulder_pitch_joint",
      "left_shoulder_roll_joint",
      "left_shoulder_yaw_joint",
      "left_elbow_joint",
      "right_shoulder_pitch_joint",
      "right_shoulder_roll_joint",
      "right_shoulder_yaw_joint",
      "right_elbow_joint",
      "waist_joint",
      "left_hip_yaw_joint",
      "left_hip_roll_joint",
      "left_hip_pitch_joint",
      "left_knee_joint",
      "left_ankle_pitch_joint",
      "left_ankle_roll_joint",
      "right_hip_yaw_joint",
      "right_hip_roll_joint",
      "right_hip_pitch_joint",
      "right_knee_joint",
      "right_ankle_pitch_joint",
      "right_ankle_roll_joint",
    ]
  upper_dof_names:
    [
      "left_shoulder_pitch_joint",
      "left_shoulder_roll_joint",
      "left_shoulder_yaw_joint",
      "left_elbow_joint",
      "right_shoulder_pitch_joint",
      "right_shoulder_roll_joint",
      "right_shoulder_yaw_joint",
      "right_elbow_joint",
    ]
  upper_left_arm_dof_names:
    [
      "left_shoulder_pitch_joint",
      "left_shoulder_roll_joint",
      "left_shoulder_yaw_joint",
      "left_elbow_joint",
    ]
  upper_right_arm_dof_names:
    [
      "right_shoulder_pitch_joint",
      "right_shoulder_roll_joint",
      "right_shoulder_yaw_joint",
      "right_elbow_joint",
    ]
  lower_dof_names:
    [
      "left_hip_yaw_joint",
      "left_hip_roll_joint",
      "left_hip_pitch_joint",
      "left_knee_joint",
      "left_ankle_pitch_joint",
      "left_ankle_roll_joint",
      "right_hip_yaw_joint",
      "right_hip_roll_joint",
      "right_hip_pitch_joint",
      "right_knee_joint",
      "right_ankle_pitch_joint",
      "right_ankle_roll_joint",
      "waist_joint",
    ]
  waist_dof_names: ["waist_joint"]
  dof_pos_lower_limit_list:
    [
      -3.31,
      -0.1,
      -2.94,
      -2.09,
      -3.31,
      -3.14,
      -2.94,
      -2.09,
      -0.523,
      -0.15,
      -0.436,
      -2.0,
      0.3,
      -0.698,
      -0.331,
      -0.15,
      -0.436,
      -2.0,
      0.3,
      -0.698,
      -0.331,
    ]
  dof_pos_upper_limit_list:
    [
      1.22,
      3.14,
      2.94,
      -0.2,
      1.22,
      0.1,
      2.94,
      -0.2,
      0.523,
      0.15,
      0.436,
      0.436,
      2.0,
      0.525,
      0.331,
      0.15,
      0.436,
      0.436,
      2.0,
      0.525,
      0.331,
    ]
  dof_vel_limit_list:
    [
      3.56,
      3.56,
      3.56,
      3.66,
      3.56,
      3.56,
      3.56,
      3.66,
      12.21,
      12.21,
      10.47,
      10.47,
      10.47,
      12.56,
      12.56,
      12.2,
      10.47,
      10.47,
      10.47,
      12.56,
      12.56,
    ]

  dof_effort_limit_list:
    [
      57.0,
      57.0,
      57.0,
      31.0,
      57.0,
      57.0,
      57.0,
      31.0,
      96.0,
      96.0,
      216.0,
      216.0,
      216.0,
      40.0,
      40.0,
      96.0,
      216.0,
      216.0,
      216.0,
      40.0,
      40.0,
    ]
  # only apply for isaacsim
  dof_armature_list:
    [
      0.03,
      0.03,
      0.03,
      0.03,
      0.03,
      0.03,

      0.03,
      0.03,
      0.03,
      0.03,
      0.03,
      0.03,

      0.03,

      0.03,
      0.03,
      0.03,
      0.03,

      0.04,
      0.03,
      0.03,
      0.03,
    ]
  # only apply for isaacsim
  dof_joint_friction_list:
    [
      0.03,
      0.03,
      0.03,
      0.03,
      0.03,
      0.03,

      0.03,
      0.03,
      0.03,
      0.03,
      0.03,
      0.03,

      0.03,

      0.03,
      0.03,
      0.03,
      0.03,

      0.03,
      0.03,
      0.03,
      0.03,
    ]

  body_names:
    [
      "base_link",

      "left_shoulder_pitch_link",
      "left_shoulder_roll_link",
      "left_shoulder_yaw_link",
      "left_elbow_link",

      "right_shoulder_pitch_link",
      "right_shoulder_roll_link",
      "right_shoulder_yaw_link",
      "right_elbow_link",

      "waist_link",

      "left_hip_yaw_link",
      "left_hip_roll_link",
      "left_hip_pitch_link",
      "left_knee_link",
      "left_ankle_pitch_link",
      "left_ankle_roll_link",

      "right_hip_yaw_link",
      "right_hip_roll_link",
      "right_hip_pitch_link",
      "right_knee_link",
      "right_ankle_pitch_link",
      "right_ankle_roll_link",
    ]

  reset_bodies:
    [
      "base_link",

      "left_shoulder_pitch_link",
      "left_shoulder_roll_link",
      "left_shoulder_yaw_link",
      "left_elbow_link",

      "right_shoulder_pitch_link",
      "right_shoulder_roll_link",
      "right_shoulder_yaw_link",
      "right_elbow_link",

      "waist_link",

      "left_hip_yaw_link",
      "left_hip_roll_link",
      "left_hip_pitch_link",
      "left_knee_link",
      "left_ankle_pitch_link",
      "left_ankle_roll_link",

      "right_hip_yaw_link",
      "right_hip_roll_link",
      "right_hip_pitch_link",
      "right_knee_link",
      "right_ankle_pitch_link",
      "right_ankle_roll_link",
    ]

  terminate_after_contacts_on: ["waist_link", "shoulder", "hip"]
  penalize_contacts_on: ["waist_link", "shoulder", "hip"]
  init_state:
    pos: [0.0, 0.0, 1.01] # x,y,z [m]
    rot: [0.0, 0.0, 0.0, 1.0] # x,y,z,w [quat]
    lin_vel: [0.0, 0.0, 0.0] # x,y,z [m/s]
    ang_vel: [0.0, 0.0, 0.0] # x,y,z [rad/s]
    default_joint_angles: # = target angles [rad] when action = 0.0
      left_shoulder_pitch_joint: 0.
      left_shoulder_roll_joint: 0.1
      left_shoulder_yaw_joint: 0.
      left_elbow_joint: -0.2

      right_shoulder_pitch_joint: 0.
      right_shoulder_roll_joint: -0.1
      right_shoulder_yaw_joint: 0.
      right_elbow_joint: -0.2

      waist_joint: 0.

      left_hip_yaw_joint: 0.
      left_hip_roll_joint: 0.
      left_hip_pitch_joint: -0.1
      left_knee_joint: 0.3
      left_ankle_pitch_joint: -0.2
      left_ankle_roll_joint: 0.

      right_hip_yaw_joint: 0.
      right_hip_roll_joint: 0.
      right_hip_pitch_joint: -0.1
      right_knee_joint: 0.3
      right_ankle_pitch_joint: -0.2
      right_ankle_roll_joint: 0.

  randomize_link_body_names:
    [
      "waist_link",
      "left_hip_yaw_link",
      "left_hip_roll_link",
      "left_hip_pitch_link",
      "left_knee_link",
      "right_hip_yaw_link",
      "right_hip_roll_link",
      "right_hip_pitch_link",
      "right_knee_link",
    ]

  control:
    actuator_network_path: null
    control_type: P

    stiffness: # [N*m/rad]
      hip_yaw: 100
      hip_roll: 100
      hip_pitch: 100
      knee: 200
      ankle_pitch: 20
      ankle_roll: 20
      waist: 400
      shoulder_pitch: 90
      shoulder_roll: 60
      shoulder_yaw: 20
      elbow: 60

    damping: # [N*m/rad]  # [N*m*s/rad]
      hip_yaw: 2.5
      hip_roll: 2.5
      hip_pitch: 2.5
      knee: 5.0
      ankle_pitch: 0.2
      ankle_roll: 0.1
      waist: 5.0
      shoulder_pitch: 2.0
      shoulder_roll: 1.0
      shoulder_yaw: 0.4
      elbow: 1.0

    # action scale: target angle = actionScale * action + defaultAngle
    action_scale: 0.25
    action_clip_value: 100.0
    clip_torques: False

  asset:
    disable_gravity: false
    collapse_fixed_joints: True # merge bodies connected by fixed joints. Specific fixed joints can be kept by adding " <... dont_collapse="true">
    replace_cylinder_with_capsule: True
    flip_visual_attachments: False
    armature: 0.001 # isaacgym armature is set by this
    thickness: 0.01
    max_angular_velocity: 1000.
    max_linear_velocity: 1000.
    density: 0.001
    angular_damping: 0.
    linear_damping: 0.

    robot_type: hi2_21dof
    asset_root: "./"
    urdf_file: "assets/robots/ZJ-Humanoid/hi2/21dof/hi2_21dof.urdf"
    xml_file: "assets/robots/ZJ-Humanoid/hi2/21dof/hi2_21dof.xml"
    self_collisions: 0 # 1 to disable, 0 to enable self collisions
    default_dof_drive_mode: 3

    fix_base_link: False # TEST: fix base link to world

  motion:
    max_frame_length: 1000 # 16s
    min_frame_length: 100 # 2s
    single_motion_flag: True
    motion_file: ${motion_lmdb_path}
    handpicked_motion_names: []
    excluded_motion_names: []
    num_workers: 1 # Number of workers for parallel motion loading. Set to 1 for sequential loading.
    asset:
      assetRoot: "./"
      assetFileName: "assets/robots/ZJ-Humanoid/hi2/21dof/retargeting_hi2_21dof.xml"

    humanoid_type: hi2
    bias_offset: False
    has_self_collision: True
    has_mesh: False
    has_jt_limit: False
    has_dof_subset: True
    has_upright_start: True
    has_smpl_pd_offset: False
    remove_toe: False # For humanoid's geom toe
    motion_sym_loss: False
    sym_loss_coef: 1
    big_ankle: True

    has_shape_obs: false
    has_shape_obs_disc: false
    has_shape_variation: False

    masterfoot: False
    freeze_toe: false
    freeze_hand: False
    box_body: True
    real_weight: True
    real_weight_porpotion_capsules: True
    real_weight_porpotion_boxes: True

    body_names: ${robot.body_names}
    key_bodies: ${robot.key_bodies}

    limb_weight_group:
      - [
          "left_hip_pitch_link",
          "left_hip_roll_link",
          "left_hip_yaw_link",
          "left_knee_link",
          "left_ankle_pitch_link",
          "left_ankle_roll_link",
        ]
      - [
          "right_hip_pitch_link",
          "right_hip_roll_link",
          "right_hip_yaw_link",
          "right_knee_link",
          "right_ankle_pitch_link",
          "right_ankle_roll_link",
        ]
      - ["waist_link", "base_link"]
      - [
          "left_shoulder_pitch_link",
          "left_shoulder_roll_link",
          "left_shoulder_yaw_link",
          "left_elbow_link",
        ]
      - [
          "right_shoulder_pitch_link",
          "right_shoulder_roll_link",
          "right_shoulder_yaw_link",
          "right_elbow_link",
        ]

    dof_names: ${robot.dof_names}
    right_foot_name: "r_foot_roll"
    left_foot_name: "l_foot_roll"

    num_extend_bodies: 3
    extend_config:
      - joint_name: "left_hand_link"
        parent_name: "left_elbow_link"
        pos: [0.0, 0.0, -0.405]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      - joint_name: "right_hand_link"
        parent_name: "right_elbow_link"
        pos: [0.0, 0.0, -0.405]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      - joint_name: "head_link"
        parent_name: "base_link"
        pos: [0.0, 0.0, 0.55]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z

    motion_tracking_link:
      - "left_hand_link"
      - "right_hand_link"
      - "head_link"

    hand_link:
      - "left_hand_link"
      - "right_hand_link"

    lower_body_link:
      - "waist_link"
      - "left_hip_pitch_link"
      - "left_hip_roll_link"
      - "left_hip_yaw_link"
      - "left_knee_link"
      - "left_ankle_pitch_link"
      - "left_ankle_roll_link"
      - "right_hip_pitch_link"
      - "right_hip_roll_link"
      - "right_hip_yaw_link"
      - "right_knee_link"
      - "right_ankle_pitch_link"
      - "right_ankle_roll_link"
      - "base_link"

    upper_body_link:
      - "left_shoulder_pitch_link"
      - "left_shoulder_roll_link"
      - "left_shoulder_yaw_link"
      - "left_elbow_link"
      - "right_shoulder_pitch_link"
      - "right_shoulder_roll_link"
      - "right_shoulder_yaw_link"
      - "right_elbow_link"
      - "left_hand_link"
      - "right_hand_link"
      - "head_link"

    lower_body_joint_ids:
      - "left_hip_pitch_joint"
      - "left_hip_roll_joint"
      - "left_hip_yaw_joint"
      - "left_knee_joint"
      - "left_ankle_pitch_joint"
      - "left_ankle_roll_joint"
      - "right_hip_pitch_joint"
      - "right_hip_roll_joint"
      - "right_hip_yaw_joint"
      - "right_knee_joint"
      - "right_ankle_pitch_joint"
      - "right_ankle_roll_joint"

    upper_body_joint_ids:
      - "left_shoulder_pitch_joint"
      - "left_shoulder_roll_joint"
      - "left_shoulder_yaw_joint"
      - "left_elbow_joint"
      - "waist_joint"
      - "right_shoulder_pitch_joint"
      - "right_shoulder_roll_joint"
      - "right_shoulder_yaw_joint"
      - "right_elbow_joint"

    pelvis_link: "waist_link"
    base_link: "base_link"
    hips_link:
      - "left_hip_pitch_link"
      - "left_hip_roll_link"
      - "left_hip_yaw_link"
      - "right_hip_pitch_link"
      - "right_hip_roll_link"
      - "right_hip_yaw_link"

    joint_matches:
      - ["waist_link", "Pelvis"]
      - ["left_hip_pitch_link", "L_Hip"]
      - ["left_knee_link", "L_Knee"]
      - ["left_ankle_roll_link", "L_Ankle"]
      - ["right_hip_pitch_link", "R_Hip"]
      - ["right_knee_link", "R_Knee"]
      - ["right_ankle_roll_link", "R_Ankle"]
      - ["left_shoulder_roll_link", "L_Shoulder"]
      - ["left_elbow_link", "L_Elbow"]
      - ["left_hand_link", "L_Hand"]
      - ["right_shoulder_roll_link", "R_Shoulder"]
      - ["right_elbow_link", "R_Elbow"]
      - ["right_hand_link", "R_Hand"]
      - ["head_link", "Head"]

    smpl_pose_modifier:
      - Pelvis: "[np.pi/2, 0, np.pi/2]"
      - L_Shoulder: "[0, 0, -np.pi/2]"
      - R_Shoulder: "[0, 0, np.pi/2]"
      # - L_Elbow: "[0, -np.pi/2, 0]"
      # - R_Elbow: "[0, np.pi/2, 0]"

    visualization:
      customize_color: True
      marker_joint_colors:
        - [0.239, 0.447, 0.922] # pelvis
        - [0.239, 0.447, 0.922] # left_hip_yaw_joint
        - [0.239, 0.447, 0.922] # left_hip_roll_joint
        - [0.239, 0.447, 0.922] # left_hip_pitch_joint
        - [0.239, 0.447, 0.922] # left_knee_joint
        - [0.239, 0.447, 0.922] # left_ankle_pitch_joint
        - [0.239, 0.447, 0.922] # left_ankle_roll_joint
        - [0.239, 0.447, 0.922] # right_hip_yaw_joint
        - [0.239, 0.447, 0.922] # right_hip_roll_joint
        - [0.239, 0.447, 0.922] # right_hip_pitch_joint
        - [0.239, 0.447, 0.922] # right_knee_joint
        - [0.239, 0.447, 0.922] # right_ankle_pitch_joint
        - [0.239, 0.447, 0.922] # right_ankle_roll_joint
        - [0.239, 0.447, 0.922] # waist_joint
        - [0.239, 0.447, 0.922] # left_shoulder_pitch_joint
        - [0.239, 0.447, 0.922] # left_shoulder_roll_joint
        - [0.239, 0.447, 0.922] # left_shoulder_yaw_joint
        - [0.239, 0.447, 0.922] # left_elbow_joint
        - [0.239, 0.447, 0.922] # right_shoulder_pitch_joint
        - [0.239, 0.447, 0.922] # right_shoulder_roll_joint
        - [0.239, 0.447, 0.922] # right_shoulder_yaw_joint
        - [0.239, 0.447, 0.922] # right_elbow_joint
        - [0.929, 0.341, 0.298] # left_elbow_joint_extend
        - [0.929, 0.341, 0.298] # right_elbow_joint_extend
        - [0.929, 0.341, 0.298] # head_link

