handpicked_motion_names:
  - 0-DanceDB_20120731_StefanosTheodorou_Stefanos_1os_antrikos_karsilamas_C3D_stageii
  - 0-DanceDB_20120731_StefanosTheodorou_Stefanos_2os_antrikos_karsilamas_C3D_stageii
  - 0-DanceDB_20120731_StefanosTheodorou_Stefanos_3os_antrikos_karsilamas_C3D_stageii
  - 0-DanceDB_20120731_StefanosTheodorou_Stefanos_Zeibekiko_CY_C3D_stageii
  - 0-DanceDB_20120805_VasoAristeidou_Vaso_Aristeidou_Zeimpekiko_v1_stageii
  - 0-DanceDB_20120805_VasoAristeidou_Vasso_Aristidou_Hasapiko_stageii
  - 0-DanceDB_20120807_CliodelaVara_Clio_Flamenco_C3D_stageii
  - 0-DanceDB_20120807_CliodelaVara_Clio_Haniotikos_C3D_stageii
  - 0-DanceDB_20120807_CliodelaVara_Clio_Maleviziotikos_stageii
  - 0-DanceDB_20120807_VasoAristeidou_Vasso_Bachata_01_stageii
  - 0-DanceDB_20120807_VasoAristeidou_Vasso_Reggaeton_01_stageii
  - 0-DanceDB_20120807_VasoAristeidou_Vasso_Salsa_Shines_01_stageii
  - 0-DanceDB_20120911_TheodorosSourmelis_Capoeira_Theodoros_v2_C3D_stageii
  - 0-DanceDB_20120911_TheodorosSourmelis_Capoeira_Theodoros_v3_C3D_stageii
  - 0-DanceDB_20130216_AnnaCharalambous_Anna_Angry_C3D_stageii
  - 0-DanceDB_20130216_AnnaCharalambous_Anna_Curiosity_C3D_stageii
  - 0-DanceDB_20130216_AnnaCharalambous_Anna_Happy_C3D_stageii
  - 0-DanceDB_20130216_AnnaCharalambous_Anna_Nervous_C3D_stageii
  - 0-DanceDB_20130216_AnnaCharalambous_Anna_Sad_C3D_stageii
  - 0-DanceDB_20130216_AnnaCharalambous_Anna_Scary_C3D_stageii
  - 0-DanceDB_20131001_OliviaKyriakides_Olivia_Annoyed_C3D_stageii
  - 0-DanceDB_20131001_OliviaKyriakides_Olivia_Bored_C3D_stageii
  - 0-DanceDB_20131001_OliviaKyriakides_Olivia_Excited_C3D_stageii
  - 0-DanceDB_20131001_OliviaKyriakides_Olivia_Happy_C3D_stageii
  - 0-DanceDB_20131001_OliviaKyriakides_Olivia_Miserable_C3D_stageii
  - 0-DanceDB_20131001_OliviaKyriakides_Olivia_Mix_C3D_stageii
  - 0-DanceDB_20131001_OliviaKyriakides_Olivia_Pleased_C3D_stageii
  - 0-DanceDB_20131001_OliviaKyriakides_Olivia_Relaxed_C3D_stageii
  - 0-DanceDB_20131001_OliviaKyriakides_Olivia_Sad_C3D_stageii
  - 0-DanceDB_20131001_OliviaKyriakides_Olivia_Satisfied_C3D_stageii
  - 0-DanceDB_20131001_OliviaKyriakides_Olivia_Tired_C3D_stageii
  - 0-DanceDB_20131001_SophieKamenou_Sophie_Afraid_C3D_stageii
  - 0-DanceDB_20131001_SophieKamenou_Sophie_Bored_C3D_stageii
  - 0-DanceDB_20131001_SophieKamenou_Sophie_Excited_C3D_stageii
  - 0-DanceDB_20131001_SophieKamenou_Sophie_Happy_C3D_stageii
  - 0-DanceDB_20131001_SophieKamenou_Sophie_Tired_C3D_stageii
  - 0-DanceDB_20131001_TheodoraTsiakka_Theodora_Afraid_C3D_stageii
  - 0-DanceDB_20131001_TheodoraTsiakka_Theodora_Bored_C3D_stageii
  - 0-DanceDB_20131001_TheodoraTsiakka_Theodora_Excited_C3D_stageii
  - 0-DanceDB_20131001_TheodoraTsiakka_Theodora_Happy_C3D_stageii
  - 0-DanceDB_20131001_TheodoraTsiakka_Theodora_Miserable_C3D_stageii
  - 0-DanceDB_20180501_CliodelaVara_CLIO_Zorbas_stageii
  - 0-DanceDB_20180501_CliodelaVara_CLIO_Roditikos_stageii
  - 0-DanceDB_20180501_CliodelaVara_CLIO_Rasopoulos_stageii
  - 0-DanceDB_20180501_CliodelaVara_CLIO_Podaraki_stageii
  - 0-DanceDB_20180501_CliodelaVara_CLIO_Pastirske_stageii
  - 0-DanceDB_20180501_CliodelaVara_CLIO_Outsai_stageii
  - 0-DanceDB_20180501_CliodelaVara_CLIO_Laziotikos_stageii
  - 0-DanceDB_20180501_CliodelaVara_CLIO_Kolo_stageii
  - 0-DanceDB_20180501_CliodelaVara_CLIO_Dimitroula_1_stageii
  - 0-DanceDB_20180501_AndreasdelaVara_ANDREAS_Zeibekiko_stageii
  - 0-DanceDB_20180501_AndreasdelaVara_ANDREAS_Zaloggo_stageii
  - 0-DanceDB_20180501_AndreasdelaVara_ANDREAS_Tsesto_Zonaradiko_stageii
  - 0-DanceDB_20180501_AndreasdelaVara_ANDREAS_Tsamiko_stageii
  - 0-DanceDB_20180501_AndreasdelaVara_ANDREAS_Tatsia_stageii
  - 0-DanceDB_20180501_AndreasdelaVara_ANDREAS_Sta_tria_Syrtos_stageii
  - 0-DanceDB_20180501_AndreasdelaVara_ANDREAS_Hasaposerviko_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Tired_v2_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Tired_v1_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Satisfied_v2_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Satisfied_v1_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Sad_v2_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Relaxed_v2_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Relaxed_v1_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Pleased_v2_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Pleased_v1_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Neutral_v2_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Miserable_v2_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Miserable_v1_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Happy_v2_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Happy_v1_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Excited_v2_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Excited_v1_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Bored_v2_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Bored_v1_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Annoyed_v2_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Annoyed_v1_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Angry_v2_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Angry_v1_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Afraid_v2_C3D_stageii
  - 0-DanceDB_20151003_ElenaKyriakou_Elena_Afraid_v1_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Tired_v2_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Tired_v1_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Satisfied_v2_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Satisfied_v1_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Sad_v2_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Sad_v1_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Relaxed_v2_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Relaxed_v1_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Pleased_v2_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Pleased_v1_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Miserable_v1_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Happy_v2_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Happy_v1_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Excited_v2_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Excited_v1_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Bored_v2_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Bored_v1_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Annoyed_v2_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Annoyed_v1_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Angry_v2_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Angry_v1_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Afraid_v2_C3D_stageii
  - 0-DanceDB_20151003_AndriaMichaelidou_Andria_Afraid_v1_C3D_stageii
  - 0-DanceDB_20150927_VasoAristeidou_Vasso_Tired_v1_stageii
  - 0-DanceDB_20150927_VasoAristeidou_Vasso_Satisfied_v1_01_stageii
  - 0-DanceDB_20150927_VasoAristeidou_Vasso_Sad_v1_01_stageii
  - 0-DanceDB_20150927_VasoAristeidou_Vasso_Relaxed_v1_01_stageii
  - 0-DanceDB_20150927_VasoAristeidou_Vasso_Pleased_01_stageii
  - 0-DanceDB_20150927_VasoAristeidou_Vasso_Neutral_v4_01_stageii
  - 0-DanceDB_20150927_VasoAristeidou_Vasso_Neutral_v3_01_stageii
  - 0-DanceDB_20150927_VasoAristeidou_Vasso_Neutral_v2_01_stageii
  - 0-DanceDB_20150927_VasoAristeidou_Vasso_Miserable_v1_01_stageii
  - 0-DanceDB_20150927_VasoAristeidou_Vasso_Happy_v1_01_stageii
  - 0-DanceDB_20150927_VasoAristeidou_Vasso_Excited_v1_01_stageii
  - 0-DanceDB_20150927_VasoAristeidou_Vasso_Bored_v1_01_stageii
  - 0-DanceDB_20150927_VasoAristeidou_Vasso_Annoyed_v1_01_stageii
  - 0-DanceDB_20150927_VasoAristeidou_Vasso_Angry_v1_01_stageii
  - 0-DanceDB_20150927_VasoAristeidou_Vasso_Afraid_v1_01_stageii
  - 0-DanceDB_20141230_MaritsaElia_Maritsa_Sad_C3D_stageii
  - 0-DanceDB_20141230_MaritsaElia_Maritsa_Relaxed_C3D_stageii
  - 0-DanceDB_20141230_MaritsaElia_Maritsa_Mix_C3D_stageii
  - 0-DanceDB_20141230_MaritsaElia_Maritsa_Happy_C3D_stageii
  - 0-DanceDB_20141230_MaritsaElia_Maritsa_Excited_C3D_stageii
  - 0-DanceDB_20140805_NikosMichael_Nikos_Zeibekiko_v2_C3D_stageii
  - 0-DanceDB_20140805_NikosMichael_Nikos_Zeibekiko_C3D_stageii
  - 0-DanceDB_20140526_StephanosKoullapis_StefanosKoullapis_Zeibekiko_Slow_C3D_stageii
  - 0-DanceDB_20140526_StephanosKoullapis_StefanosKoullapis_Zeibekiko_Fast_C3D_stageii
  - 0-DanceDB_20140526_StephanosKoullapis_StefanosKoullapis_Salsa_C3D_stageii
  - 0-DanceDB_20140526_StephanosKoullapis_StefanosKoullapis_Reggaeton_C3D_stageii
  - 0-DanceDB_20140526_StephanosKoullapis_StefanosKoullapis_Bachata_v2_C3D_stageii
  - 0-DanceDB_20140526_StephanosKoullapis_StefanosKoullapis_Bachata_C3D_stageii
  - 0-DanceDB_20140506_AnnaCortesi_AnnaCortesi_RandB_C3D_stageii
  - 0-DanceDB_20140121_FanieAlexandrou_Fanie_Zumba_C3D_stageii
  - 0-DanceDB_20140121_FanieAlexandrou_Fanie_MusicalTheater_C3D_stageii
  - 0-DanceDB_20140121_FanieAlexandrou_Fanie_Hiphop_C3D_stageii
  - 0-DanceDB_20131001_VasoAristeidou_Vasso_Tired_stageii
  - 0-DanceDB_20131001_VasoAristeidou_Vasso_Satisfied_01_stageii
  - 0-DanceDB_20131001_VasoAristeidou_Vasso_Sad_01_stageii
  - 0-DanceDB_20131001_VasoAristeidou_Vasso_Relaxed_01_stageii
  - 0-DanceDB_20131001_VasoAristeidou_Vasso_Mix_01_stageii
  - 0-DanceDB_20131001_VasoAristeidou_Vasso_Miserable_01_stageii
  - 0-DanceDB_20131001_VasoAristeidou_Vasso_Happy_01_stageii
  - 0-DanceDB_20131001_VasoAristeidou_Vasso_Excited_01_stageii
  - 0-DanceDB_20131001_VasoAristeidou_Vasso_Bored_01_stageii
  - 0-DanceDB_20131001_VasoAristeidou_Vasso_Annoyed_01_stageii
  - 0-DanceDB_20131001_VasoAristeidou_Vasso_Angry_01_stageii
  - 0-DanceDB_20131001_VasoAristeidou_Vasso_Afraid_01_stageii
  - 0-DanceDB_20131001_TheodoraTsiakka_Theodora_Tired_C3D_stageii
  - 0-DanceDB_20131001_TheodoraTsiakka_Theodora_Pleased_C3D_stageii
  - 0-DanceDB_20131001_TheodoraTsiakka_Theodora_Mix_C3D_stageii
  - 0-Transitions_mazen_c3d_dance_turntwist180_stageii
  - 0-Transitions_mazen_c3d_dance_jumpinplace_stageii
  - 0-Transitions_mazen_c3d_dance_kick_stageii
  - 0-Transitions_mazen_c3d_dance_longjump_stageii
  - 0-Transitions_mazen_c3d_dance_push_stageii
  - 0-Transitions_mazen_c3d_dance_runbackwards_stageii
  - 0-Transitions_mazen_c3d_dance_running_stageii
  - 0-Transitions_mazen_c3d_dance_stand_stageii
  - 0-Transitions_mazen_c3d_dance_walk_stageii
  - 0-Transitions_mazen_c3d_devishdance_jumpinplace_stageii
  - 0-Transitions_mazen_c3d_devishdance_kick_stageii
  - 0-Transitions_mazen_c3d_devishdance_longjump_stageii
  - 0-Transitions_mazen_c3d_devishdance_stand_stageii
  - 0-Transitions_mazen_c3d_devishdance_walkbackwards_stageii
  - 0-Transitions_mazen_c3d_twistdance_jumpingtwist360_stageii
  - 0-Transitions_mazen_c3d_twistdance_kick_stageii
  - 0-Transitions_mazen_c3d_twistdance_walk_stageii
