# @package _global_

terminations:

  time_out:
    time_out: true

  ref_gravity_projection_far:
    params:
      threshold: 0.8
      ref_prefix: ${rewards._config.reward_prefix}

  keybody_ref_z_far:
    params:
      threshold: 0.25
      ref_prefix: ${rewards._config.reward_prefix}
      keybody_names:
        - pelvis
        - left_ankle_roll_link
        - right_ankle_roll_link
        - left_wrist_yaw_link
        - right_wrist_yaw_link

  # keybody_ref_pos_far:
  #   params:
  #     threshold: 0.5
  #     ref_prefix: ${rewards._config.reward_prefix}
  #     keybody_names:
  #       - pelvis