# @package _global_

defaults:
  - /training: train_base
  - /simulator: isaacgym
  - /algo: ppo
  - /robot: unitree/G1/23dof/23dof_training
  - /env: motion_tracking
  - /env/observations: motion_tracking/obs_unitree_g1_23dof_ppo_teacher
  - /env/rewards: motion_tracking/rew_g1_23dof_stage1
  - /env/domain_randomization: NO_domain_rand
  - /env/terrain: plane

project_name: HoloMotion

motion_lmdb_path: ???
# checkpoint: ???