robot:
  fitted_shape_dump_path: "assets/robots/${robot.humanoid_type}/fitted_smpl_shape.pkl"
  asset:
    smpl_dir: "assets/smpl"
    assetRoot: "./"
    assetFileName: ???
    training_mjcfName: ???

motion_pkl_root: null
motion_name: null
video_dir: ${motion_pkl_root}/video_rendering
skip_frames: 3 # when skip frames=1, it means 30hz, when skip frames=2, it means 15hz, etc.
show_markers: False
max_workers: 12
