defaults:
  - retargeting_base

robot:
  humanoid_type: ZJ-Humanoid/hi2/21dof

  asset:
    assetFileName: "assets/robots/${robot.humanoid_type}/retargeting_hi2_21dof.xml"

  extend_config:
    - joint_name: "left_hand_link"
      parent_name: "left_elbow_link"
      pos: [0.0, 0.0, -0.405]
      rot: [1.0, 0.0, 0.0, 0.0] # w x y z
    - joint_name: "right_hand_link"
      parent_name: "right_elbow_link"
      pos: [0.0, 0.0, -0.405]
      rot: [1.0, 0.0, 0.0, 0.0] # w x y z
    - joint_name: "head_link"
      parent_name: "base_link"
      pos: [0.0, 0.0, 0.55]
      rot: [1.0, 0.0, 0.0, 0.0] # w x y z

  # base_link: "torso_link"

  joint_matches:
    - ["waist_link", "Pelvis"]
    - ["left_hip_pitch_link", "L_Hip"]
    - ["left_knee_link", "L_Knee"]
    - ["left_ankle_roll_link", "L_Ankle"]
    - ["right_hip_pitch_link", "R_Hip"]
    - ["right_knee_link", "R_Knee"]
    - ["right_ankle_roll_link", "R_Ankle"]
    - ["left_shoulder_roll_link", "L_Shoulder"]
    - ["left_elbow_link", "L_Elbow"]
    - ["left_hand_link", "L_Hand"]
    - ["right_shoulder_roll_link", "R_Shoulder"]
    - ["right_elbow_link", "R_Elbow"]
    - ["right_hand_link", "R_Hand"]
    - ["head_link", "Head"]

  smpl_pose_modifier:
    - Pelvis: "[np.pi/2, 0, np.pi/2]"
    - L_Shoulder: "[0, 0, -np.pi/2]"
    - R_Shoulder: "[0, 0, np.pi/2]"